version: "3.4"
services:
  app:
    depends_on:
      - db
    container_name: server
    build:
      context: .
      target: unit-tests
    links:
      - db
    ports:
      - 3000:3000
    volumes:
      - "./:/usr/src/app"

  db:
    image: mongo:3.2
    container_name: mongo
    restart: unless-stopped
